### PR TITLE
fix(webpackDevServer): add history api fallback

### LINKED ISSUE #103: Fix "Cannot get *" errors
Apps using a router need the 404 to fallback to the index.html so the JS router can handle the route.  Currently, the dev server serves a literal error page.

Webpack dev server has a config for this called [`historyApiFallback`](https://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option).  It should be set to `true`.

### PR DESCRIPTION
**Pull request by levithomason**
Fixes #103 

https://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option

### CODE REVIEW

**Comment by FiberJW** [comment]
LGTM

**Comment by levithomason** [comment]
@eanplatter can we get a merge on this guy, browser refreshes are not currently possible with react-router.

**Comment by eanplatter** [comment]
LGTM

**Comment by eanplatter** [comment]
@levithomason sorry bout that. merged and published!

**Comment by FiberJW** [comment]
@eanplatter bruh

**Pull request merged**
