### PR TITLE
Add auto dep install

### LINKED ISSUE #69: Explore auto-install features and other things that can make development more convenient.
I think this guy's auto dep install is kind of neat, might be an interesting feature to think about. 

EDIT: forgot the link :P
https://github.com/insin/nwb#auto-installing-npm-dependencies

### PR DESCRIPTION
**Pull request by FiberJW**
This feature is really awesome :)
Fixes #69

### CODE REVIEW

**Comment by FiberJW** [comment]
LGTM

**Comment by FiberJW** [comment]
@eanplatter This also solves our conflict of needing to stuff enclave with common dependencies for react projects like react router. They can just require and it installs automagically :+1:

**Comment by matthiaskern** [comment]
this looks awesome! :+1:

**Comment by eanplatter** [comment]
If we auto install things we could also completely drop react from enclave's deps and not even have to worry about adding an extra step to getting started

**Comment by eanplatter** [comment]
LGTM

**Pull request merged**
