### PR TITLE
A way to test enclave out while developing.

### PR DESCRIPTION
**Pull request by eanplatter**

### CODE REVIEW

**Comment by FiberJW** [comment]
Is there a command or something that you enter when going into dev-mode?

**Comment by FiberJW** [comment]
Oh! and while you're at it on this PR, write a .md file with directions of how to run this dev env or extend it or whatever you please

**Comment by eanplatter** [comment]
@datwheat Check it out if you're up!

**Comment by eanplatter** [comment]
Gonna go ahead and merge

**Comment by FiberJW** [comment]
Ah sorry I was sleeping

**Pull request merged**
