### PR TITLE
Walkthrough

### PR DESCRIPTION
**Pull request by eanplatter**
This is a proposal for a `WALKTHROUGH.md` file. I've wanted something like this when getting into OSS, kind of like API docs but for contributing to, rather than for consuming, the API.

I essentially want to go through the library and walk through each import facet of the code.

I wanted to get some thoughts before I went through and wrote it for the whole library.

### CODE REVIEW

**Comment by FiberJW** [comment]
I like it. LGTM

**Comment by FiberJW** [comment]
bitmoji

**Comment by eanplatter** [comment]
K, I'll get it finished and then rebase!

**Comment by eanplatter** [comment]
LGTM

**Pull request merged**
