### PR TITLE
Update to babel 6

### LINKED ISSUE #8: Use babel 6
Currently I had the webpack config using babel 5 due to its simplicity, but users should be able to use babel 6  and it's configuration tools, like having a babelrc file.

### PR DESCRIPTION
**Pull request by AgentEpsilon**
Added babel-core, babel-preset-react, and babel-preset-es2015
as dependencies. Also updated babel-loader to v6.
Added .babelrc with presets react and es2015.

Fixes #8

### CODE REVIEW

**Comment by FiberJW** [comment]
Is there not a need to change the loader in the webpack config? Try this out in the example to test if this works and report it here

**Comment by AgentEpsilon** [comment]
Nope - it's the same loader (`babel-loader`), just an updated version. Webpack config doesn't change.
And I already tested it _before_ I submitted the PR. Works fine for me.

**Comment by FiberJW** [comment]
Sweet. You've got a thumbs up from me. @eanplatter ?

**Comment by eanplatter** [comment]
Looks like a good start!

**Pull request merged**
